### PR TITLE
Add CUI section

### PR DESCRIPTION
**Pull request by myd7349**
This idea comes from [awesome-go](https://github.com/avelino/awesome-go).

### CODE REVIEW

**Comment by fffaraz** [comment]
Thanks.

**Comment by netpoetica** [comment]
I've never heard it referred to as a "CUI" before - is that common? CLI I believe is the much more popular name for it. I would even go so far as to say, there shouldn't be a section with a TLA/acronym, should be spelled out all the way. Section title: "Command Line Interface". What do you guys think?

**Comment by fffaraz** [comment]
I definitely agree with you. That's why I mentioned "CLI" keyword in it's description. Maybe they just wanted to name it similar to GUI. That's graphical interface and it's console interface!

**Comment by myd7349** [comment]
@netpoetica you are right. CLI is better than CUI.

**Pull request merged**
