### PR TITLE
add cuda-related libs nccl, cub, moderngpu

### PR DESCRIPTION
**Pull request by CheYulin**
Add following three libraries in concurrency section:

* [Nccl](https://github.com/NVIDIA/nccl) - Optimized primitives for collective multi-GPU communication. [Copyright (c) 2015, NVIDIA CORPORATION. All rights reserved]
* [cub](https://github.com/NVlabs/cub) - CUB provides state-of-the-art, reusable software components for every layer of the CUDA programming mode. [Copyright (c) 2010-2011, Duane Merrill.  All rights reserved. Copyright (c) 2011-2016, NVIDIA CORPORATION.  All rights reserved.]
* [moderngpu](https://github.com/moderngpu/moderngpu) - moderngpu is a productivity library for general-purpose computing on GPUs. It is a header-only C++ library written for CUDA. The unique value of the library is in its accelerated primitives for solving irregularly parallel problems. [ Copyright (c) 2016, Sean Baxter All rights reserved.]

### CODE REVIEW

**Comment by fffaraz** [comment]
Please follow the alphabetical order

**Comment by fffaraz** [comment]
And copyrights don't have to be that long.

**Comment by CheYulin** [comment]
Hi, @fffaraz , I have followed your advice and committed a patch.

**Comment by Kojoley** [comment]
From the https://github.com/NVIDIA/nccl/blob/master/README.md
>NCCL is provided under the **BSD licence**.

From the https://github.com/NVlabs/cub/blob/1.5.2/LICENSE.TXT
> CUB is available under the **"New BSD" open-source license**:

According to https://github.com/moderngpu/moderngpu/blob/master/LICENSE.md - it is licensed under the 2-clause BSD license (FreeBSD License). But I think clarification from the author of the library is needed.
> The views and conclusions contained in the software and documentation are those
> of the authors and should not be interpreted as representing official policies,
> either expressed or implied, of the **FreeBSD Project**.

**Comment by Kojoley** [comment]
Also NCCL and CUB are spelled in the uppercase.

**Comment by CheYulin** [comment]
@Kojoley  , thanks for your suggestion, I have followed your suggestion to update the license and uppercased the NCCL and CUB.

**Pull request merged**
