### PR TITLE
Add jest

### PR DESCRIPTION
**Pull request by jeaye**

### CODE REVIEW

**Comment by jeaye** [comment]
There is no other unit testing framework in the list that uses only recursive templates and not a single macro. Furthermore, not many will be using C++14. Please either merge this or close it; leaving it indefinitely open isn't going to help.

**Comment by jeaye** [comment]
Any update on this one?

**Comment by fffaraz** [comment]
Looks like the project is not active anymore and has too few stars.

**Comment by fffaraz** [comment]
I added it into https://github.com/fffaraz/awesome-cpp/blob/master/minor.md

**Comment by jeaye** [comment]
Sounds good!

**Pull request closed without merging**
