### PR TITLE
Add PVS-Studio static analyzer.

### PR DESCRIPTION
**Pull request by SvyatoslavRazmyslov**
Hello! We develop a static code analyzer PVS-Studio for C/C++ and C#. It would be great if you include our analyzer in this list.

### CODE REVIEW

**Comment by francescogomez** [comment]
И сюда добрались коммерческие дьябло!

**Comment by SvyatoslavRazmyslov** [comment]
It is free for personal academic projects, open source non-commercial projects and independent projects of individual developers.

**Comment by polyvertex** [comment]
@SvyatoslavRazmyslov does your product come with its source code, at least for its "free" variants?

**Comment by SvyatoslavRazmyslov** [comment]
@polyvertex the source code of the analyzer is closed. To use the tool for free, just download and install the binary version from the site. You will find a detailed explanation of the free use of the tool in [this](http://www.viva64.com/en/b/0457/) article.

**Comment by ChaoMai** [comment]
@polyvertex @francescogomez This repo is just a collection of awesome thing about C++ and it's not the "free awesome-cpp".

There also is Microsoft Visual Studio, Clion, AppCode in the [fffaraz/awesome-cpp: Integrated Development Environment](https://github.com/fffaraz/awesome-cpp/blob/master/README.md#integrated-development-environment) part, which aren't free or open source software.

**Comment by polyvertex** [comment]
@SvyatoslavRazmyslov Unless I'm mistaken, the resources listed in this repo all have their source code available, including the commercial ones. IMHO it would be a mistake to accept this PR as it would break the implicit "rule" of this list awesome list.

**Comment by polyvertex** [comment]
@ChaoMai Obviously I have missed the VS case. For what it's worth, I still believe pushing commercial products here would be a mistake.

**Comment by fffaraz** [comment]
It's a tool not a library. It would be better if it was open source but it doesn't have to. Visual studio, Xcode, Microsoft's and Intel's compilers are not open source either.

**Pull request merged**
