### PR TITLE
Added Fido Machine Learning Library 

### PR DESCRIPTION
**Pull request by truell20**
Adds Fido, a C++ machine learning and reinforcement learning library for embedded electronics and robotics, to the machine learning category. Github: https://github.com/FidoProject/Fido. Website: http://fidoproject.github.io/.

I am a maintainer of the library and would be happy to answer any questions.

### CODE REVIEW

**Comment by jpetso** [comment]
The patch should specify the license: `[MIT]` at the end of the line, similar to other entries.

**Comment by truell20** [comment]
@jpetso. Added.

**Comment by truell20** [comment]
@fffaraz. What do you think?

**Comment by truell20** [comment]
@jpetso @fffaraz We now have ~230 stars

**Comment by jpetso** [comment]
Well, I like it, but @fffaraz is the curator :)

**Pull request merged**
