### PR TITLE
add MeTA to machine learning projects

### PR DESCRIPTION
**Pull request by smassung**

### CODE REVIEW

**Comment by fffaraz** [comment]
https://github.com/fffaraz/awesome-cpp/blob/master/CONTRIBUTING.md

**Comment by smassung** [comment]
Oops, sorry about that! Fixed now.

**Comment by fffaraz** [comment]
Not yet,
Keep the description short and simple and also it must be all in ONE LINE.

**Comment by smassung** [comment]
fixed

**Pull request merged**
