### PR TITLE
Add console-component

### PR DESCRIPTION
**Pull request by edenreich**
Hey everyone,

I would like to introduce an opensource cross-platform console component with no dependencies (using STL only).

[console-component](https://github.com/edenreich/console-component)

Preview:
**Install**:
<p align="left"></p>

**Create Project**:
<p align="left"></p>

**Usage**:
<p align="left"></p>

For all the vscoders, In addition I've also created a great vscode extension that helps to generate the cmake project and the commands using the command palette that would increase your productivity. 
And you could install this extension using the following link: [vscode-extension](https://marketplace.visualstudio.com/items?itemName=EdenReich.cpp-console-generator)

I hope some of you will find it useful for your own projects and interesting as much as I did :)

### CODE REVIEW

**Comment by MegaBor** [comment]
Good job! I can definitely see myself using this in my future projects.
Big +1 for merging this.

**Comment by MegaBor** [comment]
The vscode extension works out of the box? or do I need to clone the project?

**Comment by edenreich** [comment]
@MegaBor thanks for the feedback and yes, it works out of the box :) just install it, run the command palette and look for `cpp: create new console project`. It will then ask few questions like: project name, binary name and description. Then all you need to do is to build the project and use that other command to generate new commands

**Comment by MegaBor** [comment]
Brilliant! smart person you're! Thanks for sharing this wonderful project.

**Comment by aditya1267** [comment]
This is a great project , will surely look into it in future

**Review by adi1220 — APPROVED** [review]

**Comment by edenreich** [comment]
@fffaraz why is it closed ?

**Comment by edenreich** [comment]
@fffaraz I appreciate the hard work you putting into maintaining this project, and yet people love this library, can you please elaborate why you closed it ? and not just close it without even considering other people's opinions ?

**Pull request closed without merging**
