### PR TITLE
Add drogon to the list

### PR DESCRIPTION
**Pull request by an-tao**
[drogon](https://github.com/an-tao/drogon)

### CODE REVIEW

**Comment by myd7349** [comment]
Hi! @an-tao Thanks for your contribution.
This fixes https://github.com/fffaraz/awesome-cpp/issues/710 .
BTW, we have two more specific [Web Application Framework](https://github.com/fffaraz/awesome-cpp#web-application-framework) and [Networking](https://github.com/fffaraz/awesome-cpp#networking) categories for libraries like `Drogon`. Is it a good idea to put `Drogon` into either of these two categories?

**Comment by an-tao** [comment]
Thank you for reminding me, I will put `Drogon` into these two categories.

**Comment by an-tao** [comment]
Hi, @myd7349 
I moved `Drogon` to the `Web Application Framework` category.

**Comment by myd7349** [comment]
@an-tao Amazing! Thanks for your great work.

**Pull request merged**
