### PR TITLE
Added a new book, Programming Techniques in C++

### PR DESCRIPTION
**Pull request by rishirajsurti**

### CODE REVIEW

**Comment by eiva** [comment]
Looks like link is broken

**Comment by rishirajsurti** [comment]
@eiva Fixed.

**Comment by brainblowjob** [comment]
It is not book. It is bullshit.

**Comment by Kojoley** [comment]
```cpp
//define an iterator
list<int>::iterator it;
for(it = ll.begin(); it != ll.end(); it++){
    printf ("%d-> ", *it) ;
}
printf("\n");
```
Sorry, but no way

**Comment by rishirajsurti** [comment]
I'm amazed you said that. Did you even read it?

**Comment by rishirajsurti** [comment]
Seems like you do not refer the documentation.
Have a look: [http://www.cplusplus.com/reference/list/list/](http://www.cplusplus.com/reference/list/list/).
Here's an example for you: [http://www.cplusplus.com/reference/list/list/begin/](http://www.cplusplus.com/reference/list/list/begin/).

**Comment by rishirajsurti** [comment]
Okay. Closing this. Not enthusiastic now.

**Comment by nabijaczleweli** [comment]
lol this book, if that's the code sample from there

**Comment by brainblowjob** [comment]
@nabijaczleweli +

**Pull request closed without merging**
